"""empty message

Revision ID: 658ae988e6e5
Revises: 91e2e5895e35
Create Date: 2023-12-20 22:22:02.486905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658ae988e6e5'
down_revision = '91e2e5895e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
